### ISSUE TITLE
Explanation of configs?

### ISSUE THREAD

**Issue by Haoxiang-Wang** [modestyachts/neural_kernels_code#3]
Hi, could you explain the configs in `configs` folder? For example, among `myrtle10.yaml`, `myrtle10_exp.yaml`, `myrtle10_exp_all_chan.yaml` and `myrtle11_exp.yaml`, which one is the most powerful kernel? I'm pretty confused with the naming.

**Comment by Vaishaal** [comment]
myrtle11_exp.yaml was the best performing kernel from our paper.
