### ISSUE TITLE
Request for CIFAR10 dataset with ZCA

### ISSUE THREAD

**Issue by sunrainyg** [modestyachts/neural_kernels_code#6]
The link you provided has expired. Could you kindly provide an alternative link for downloading the dataset? Your assistance is greatly appreciated.

By the way, in the 'preprocess.py' file, it appears that there is no module named 'random_aug'.

**Comment by Vaishaal** [comment]
Unfortunately that file was deleted after I graduated, however you can use something like this: https://github.com/modestyachts/neural_kernels_code/blob/master/preprocess.py#L92-L196, load CIFAR-10 from some source (such as pytorch, convert it to npy files) to generate the ZCA-ed version.
